In [1]:
%cd src/tensorcore/

e:\Github repositories\tensorcore\src\tensorcore


In [1]:
import importlib
import tensorcore.nn

importlib.reload(tensorcore.nn)  # Reload the module

<module 'tensorcore.nn' from 'e:\\github repositories\\tensorcore\\src\\tensorcore\\nn.py'>

In [2]:
import numpy as np
import tensorcore as tc
from tensorcore import Tensor
from tensorcore import nn, optim
from tensorcore.optim import SGD
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from tensorcore.nn import sigmoid

In [3]:
# generate a binary classification data
X, y = make_moons(n_samples=1000, noise=0.1, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# convert to tensor
X_train = Tensor(X_train)
X_test = Tensor(X_test)
y_train = Tensor(y_train)
y_test = Tensor(y_test)

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((800, 2), (800,), (200, 2), (200,))

In [9]:
model = tc.Sequential([
    nn.Linear(2, 4),
    nn.Linear(4, 1)
])

optimizer = optim.SGD(model.parameters(), lr=0.001)

In [10]:
batch_size = 32
learning_rate = 0.01
max_iter = 1000
eval_interval = 100

for step in range(max_iter):
    optimizer.zero_grad()
    logits = model(X_train)                            #     ;print(logits.shape)
    logits = nn.sigmoid(logits)                       #;print(logits.shape)
    loss = nn.binary_cross_entropy(y_train, logits[:, -1])  #;print(loss.grad)
    loss.backward()
    optimizer.step()
    if step % eval_interval == 0:
        print(f"step: {step: 4} | loss: {loss}")

step:    0 | loss: Tensor(0.9714155793190002)
step:  100 | loss: Tensor(0.9676927328109741)
step:  200 | loss: Tensor(0.9639987945556641)
step:  300 | loss: Tensor(0.9603337049484253)
step:  400 | loss: Tensor(0.9566975235939026)
step:  500 | loss: Tensor(0.9530899524688721)
step:  600 | loss: Tensor(0.9495111107826233)
step:  700 | loss: Tensor(0.9459604024887085)
step:  800 | loss: Tensor(0.9424375295639038)
step:  900 | loss: Tensor(0.9389421343803406)


In [81]:
# print before
print(model.layer_list[0].weight.grad)
print(model.parameters()['layer_0'][0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Tensor([[0.5148692  0.12795998 0.6260304  0.6575927 ]
 [0.6508005  0.6033222  0.15743825 0.329808  ]])


In [86]:
# print after
print(model.layer_list[0].weight.grad)
print(model.parameters()['layer_0'][0])

[[22.47837  28.399628 37.08718  26.312988]
 [16.238914 20.516567 26.792667 19.009132]]
Tensor([[0.51037556 0.12230328 0.6186433  0.6523403 ]
 [0.64754015 0.5992181  0.15207867 0.32599717]])
